CREATE TABLE VOTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VALOR_VOTO VARCHAR(50) NOT NULL,
    DATA_VOTO TIMESTAMP NOT NULL,
    ID_PAUTA BIGINT NOT NULL,
    ID_ASSOCIADO BIGINT NOT NULL,
    CONSTRAINT FK_ID_PAUTA FOREIGN KEY (ID_PAUTA) REFERENCES PAUTAS(ID),
    CONSTRAINT FK_ID_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO) REFERENCES ASSOCIADOS(ID)
);