CREATE TABLE VOTOS (
    ID BIGINT NOT NULL,
    VALOR_VOTO VARCHAR(50) NOT NULL,
    DATA_VOTO TIMESTAMP NOT NULL,
    ID_PAUTA BIGINT NOT NULL,
    ID_VOTANTE BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ID_PAUTA FOREIGN KEY (ID_PAUTA) REFERENCES PAUTA(ID),
    CONSTRAINT FK_ID_VOTANTE FOREIGN KEY (ID_VOTANTE) REFERENCES VOTANTE(ID)
);